backend:
  name: github
  repo: YOUR_GITHUB_USER/YOUR_REPO
  branch: main
  base_url: https://YOUR-SITE.vercel.app
  auth_endpoint: /api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime", required: false }
      - { name: "description", label: "Meta Description", widget: "text", required: false }
      - { name: "image", label: "Featured Image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
